# 使用指定版本的 Node.js
FROM node:10.24.1

# 创建工作目录
WORKDIR /app

# 复制当前目录下的所有文件到工作目录
COPY . .

# 在安装 gitbook-cli 前更新 npm，并设置最大监听器数量
RUN  npm config set registry https://registry.npm.taobao.org && \
    npm install gitbook-cli -g && \
    gitbook install && \
    node -e "process.setMaxListeners(15);"  # 设置最大监听器数量为15，或者根据你的需求设置其他合适的值

# 暴露 GitBook 服务端口
EXPOSE 4000

# 设置持久化目录为 /app/data，将容器内的 /app/data 映射到主机上的 /your/host/path
VOLUME ["/app"]

# 设置启动命令
CMD ["gitbook", "serve"]