apiVersion: batch/v1
kind: Job
metadata:
  name: ha-nginx-job-hello
spec:
  template:
    spec:
      containers:
      - name: ha-nginx-job-hello-c-1
        image: nginx:1.10.1
        command:
          - "/bin/bash"
          - "-c"
          - "echo hello from ha-nginx-job-hello"
        #restartPolicy: Never
    #backoffLimit: 2

