apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
<<<<<<< HEAD
  name: gitbook-service
  namespace: gitbook
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
=======
  name: gitbook-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: gitbook
spec:
  ingressClassName: gitbook
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
>>>>>>> c71b702062e778dedfe3ddad68e48ee0890d4d90
        backend:
          service:
            name: gitbook-service
            port:
              number: 80